algoritmo "semnome"
// Função :
// Autor :
// Data : 09/05/2021
// Seção de Declarações 
var
c ,s:inteiro
 re,r ,m ,n:real
inicio
c <- 1
m <-0

escreval ("quantas vezes quer converte?")
leia(s)
enquanto (c <= s) faca
escreval ("quantos voce quer converter ?")
leia (re)

r <- re * 2.20
escreval(r)
m <- m + r
c <- c + 1

fimenquanto
escreval("o valor total é ", m)
escreval("o valor maior e ", n)
fimalgoritmo
